[build]
  publish = "."
  command = ""

[build.processing]
  skip_processing = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

